/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RelatorioPorZonasDTO { 
    mapEncomendasFreguesias?: { [key: string]: number; };
    mapEncomendasMunicipio?: { [key: string]: number; };
    mapEncomendasDistrito?: { [key: string]: number; };
    mapEncomendasPais?: { [key: string]: number; };
    mapEncomendasContinente?: { [key: string]: number; };
    totalDeEncomendas?: number;
}

