/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleSubEncomendaDTO } from './simpleSubEncomendaDTO';


export interface FullEncomendaDTO { 
    idEncomenda?: number;
    preco?: number;
    dataEncomenda?: string;
    estadoEncomenda?: FullEncomendaDTO.EstadoEncomendaEnum;
    subEncomendas?: Array<SimpleSubEncomendaDTO>;
}
export namespace FullEncomendaDTO {
    export type EstadoEncomendaEnum = 'POR_PAGAR' | 'A_PROCESSAR' | 'PROCESSADA' | 'EM_DISTRIBUICAO' | 'ENTREGUE' | 'CANCELADA';
    export const EstadoEncomendaEnum = {
        PorPagar: 'POR_PAGAR' as EstadoEncomendaEnum,
        AProcessar: 'A_PROCESSAR' as EstadoEncomendaEnum,
        Processada: 'PROCESSADA' as EstadoEncomendaEnum,
        EmDistribuicao: 'EM_DISTRIBUICAO' as EstadoEncomendaEnum,
        Entregue: 'ENTREGUE' as EstadoEncomendaEnum,
        Cancelada: 'CANCELADA' as EstadoEncomendaEnum
    };
}


