/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleUtilizadorDTO } from '../utilizador/simpleUtilizadorDTO';
import { SubEncomendaNotifDTO } from './subEncomendaNotifDTO';


export interface NotificacaoDTO { 
    idNotificacao?: number;
    subEncomenda?: SubEncomendaNotifDTO;
    tipoNotificacao?: NotificacaoDTO.TipoNotificacaoEnum;
    mensagem?: string;
    remetente?: SimpleUtilizadorDTO;
    destinatario?: SimpleUtilizadorDTO;
}
export namespace NotificacaoDTO {
    export type TipoNotificacaoEnum = 'CHEGADA_IMINENTE' | 'SAIDA_UNI_PROD' | 'NOVA_ENCOMENDA';
    export const TipoNotificacaoEnum = {
        ChegadaIminente: 'CHEGADA_IMINENTE' as TipoNotificacaoEnum,
        SaidaUniProd: 'SAIDA_UNI_PROD' as TipoNotificacaoEnum,
        NovaEncomenda: 'NOVA_ENCOMENDA' as TipoNotificacaoEnum
    };
}


