/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubItemDTO } from '../item/subItemDTO';
import { SimpleTransporteDTO } from './simpleTransporteDTO';


export interface ViagemDTO { 
    dataInicio?: string;
    dataFim?: string;
    estadoViagem?: ViagemDTO.EstadoViagemEnum;
    transporte?: SimpleTransporteDTO;
    subItems?: Array<SubItemDTO>;
}
export namespace ViagemDTO {
    export type EstadoViagemEnum = 'PROGRAMADA' | 'INICIADA' | 'FINALIZADA';
    export const EstadoViagemEnum = {
        Programada: 'PROGRAMADA' as EstadoViagemEnum,
        Iniciada: 'INICIADA' as EstadoViagemEnum,
        Finalizada: 'FINALIZADA' as EstadoViagemEnum
    };
}


