# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run:  mvn -B package --file Backend-Marketplace/pom.xml    
      
    - name: Push Docker GCR
  # You may pin to the exact commit or the version.
  # uses: RaccoonDev/push-docker-gcr@cbff6c0d9f259694f4c6bd036866eb63e1630712
      uses: RaccoonDev/push-docker-gcr@v1
      with:
        # Google Container Registry Host
        gcr_host: gcr.io/sapient-stacker-380223
        # Docker Image Name
        image_name: backend
        # Docker Image Tag
        image_tag: lat
      
